#!/usr/bin/env bash

if ! command -v rg >/dev/null 2>&1; then
	timed_log "ripgrep not found; installing...\n"
	curl -LO https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep_12.1.1_amd64.deb
	sudo dpkg -i ripgrep_12.1.1_amd64.deb
	timed_log "ripgrep installed\n"
fi
