#!/usr/bin/env bash

if ! command -v rust >/dev/null 2>&1; then
	timed_log "rust not found; installing...\n"
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
	timed_log "rust installed\n"
fi
