#!/usr/bin/env bash

process_link() {
	from=$1
	to=$2
	if [ -L "$to" ]; then
		target=$(readlink "$to")
		if ! [ "$target" = "$from" ]; then
			printf "%(%Y-%m-%d %H:%M:%S)T: Overwriting %s -> (%s -> %s)\n" -1 "$to" "$target" "$to"
			rm "$to"
			make_link "$from" "$to"
		fi
	else
		printf "%(%Y-%m-%d %H:%M:%S)T: Symlinking %s -> %s\n" -1 "$from" "$to"
		make_link "$from" "$to"
	fi
}

make_link() {
	from=$1
	to=$2
	mkdir -p "$(dirname "$to")"
	ln -s "$from" "$to"
}

declare -A mappings=()
mappings["bash/bash_profile"]=".bash_profile"
mappings["bash/bashrc"]="bashrc"
mappings["git/config"]=".config/git/config"
mappings["git/ignore"]=".config/git/ignore"
mappings["i3/config"]=".config/i3/config"
mappings["input/inputrc"]=".inputrc"
mappings["ipython/ipython_config.py"]=".ipython/profile_default/ipython_config.py"
mappings["jupyter/jupyter_notebook_config.py"]=".jupyter/jupyter_notebook_config.py"
mappings["npm/npmrc"]=".npmrc"
mappings["tmux/tmux.conf"]=".tmux.conf"
mappings["vim/vimrc"]=".vimrc"
for key in "${!mappings[@]}"; do
	from="$PATH_DOTFILES/$key"
	value="${mappings[$key]}"
	to="$HOME/$value"
	process_link "$from" "$to"
done

for filename in "$PATH_DOTFILES"/ipython/startup/*.py; do
	process_link "$filename" "$HOME/.ipython/profile_default/startup/$(basename "$filename")"
done
