repos:
  - repo: https://github.com/dycw/pre-commit-hooks
    rev: 897b3ee1f0e1bc43c1a2d634d24a7dbeae664002
    hooks:
      - id: no-commit
      - id: prettier
      - id: python
      - id: shellcheck
        exclude: bash-completion.bash
      - id: shfmt
        exclude: bash-completion.bash
      - id: text
      - id: universal
