#!/usr/bin/env bash
# shellcheck source=/dev/null

sudo apt -y install curl git

# === repo ===

export PATH_DOTFILES="${PATH_DOTFILES:-$HOME/dotfiles}"
if ! [ -d "$PATH_DOTFILES" ]; then
  git clone --recuse-submodules https://github.com/dycw/dotfiles.git "$PATH_DOTFILES"
fi

# === symlinks ===

make_link() {
  file="$1"
  link="$2"
  mkdir -p "$(dirname "$link")"
  ln -f -s "$file" "$link"
}

process_link() {
  file="$1"
  link="$2"
  if [ -f "$link" ]; then
    if [ -L "$link" ]; then
      old="$(readlink "$link")"
      if [ "$old" != "$file" ]; then
        echo "\
Re-directing symlink:
       $link
old -> $old
new -> $file"
        make_link "$file" "$link"
      fi
    else
      echo "\
Overriding existing file with symlink:
   $link
-> $file"
      make_link "$file" "$link"
    fi
  else
    echo "\
Making symlink:
   $link
-> $file"
    make_link "$file" "$link"
  fi
}

for home_name in home home.local; do
  while IFS= read -d '' -r home_path; do
    while IFS= read -d '' -r rel_path; do
      abs_path="$(realpath "$rel_path")"
      if [ -f "$abs_path" ]; then
        link="$HOME/$(realpath --relative-to="$home_path" "$abs_path")"
        process_link "$abs_path" "$link"
      fi
    done < <(find "$home_path" -print0 -type f -or -type l)
  done < <(find "$PATH_DOTFILES" -name "$home_name" -print0 -type d)
done

while IFS= read -d '' -r submodules; do
  tmux_conf="$submodules/.tmux/.tmux.conf"
  if [ -f "$tmux_conf" ]; then
    process_link "$tmux_conf" "$HOME/.tmux.conf"
  fi
done < <(find "$PATH_DOTFILES" -name submodules -not -path "*/.git/*" -print0 -type d)

# === brew ===

linuxbrew="/home/linuxbrew"
if ! [ -d "$linuxbrew" ]; then
  curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
fi
sudo apt -y install build-essential
brew install \
  bandwhich \
  bat \
  bingrep \
  broot \
  gcc \
  ddgr \
  direnv \
  diskonaut \
  dust \
  elm \
  exa \
  fd \
  fpp \
  fzf \
  git \
  git-crypt \
  git-delta \
  go \
  googler \
  grex \
  hub \
  hyperfine \
  mdcat \
  neovim \
  node \
  pipx \
  procs \
  pyenv \
  ranger \
  ripgrep \
  sd \
  shellcheck \
  shfmt \
  speedtest-cli \
  spotify-tui \
  starship \
  tealdeer \
  tmux \
  tokei \
  tree \
  watchexec \
  yarn \
  zoxide \
  zsh \
  clementtsang/bottom/bottom \
  eth-p/software/bat-extras \
  bzip2 libffi libxml2 libxmlsec1 openssl readline sqlite xz zlib # pyenv
brew install universal-ctags/universal-ctags/universal-ctags --HEAD

# === cargo ===

cargo install \
  gitui \
  gitweb \
  rmesg

# === dropbox ===

data_dir=/data/derek
if [ -d "$data_dir" ]; then
  dropboxd="$data_dir/.dropbox-dist/dropboxd"
  if ! [ -f "$dropboxd" ]; then
    cd "$data_dir" || exit
    wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
    HOME="$data_dir" "$dropboxd"
  fi
fi

# === fzf ===

install="$(brew --prefix)/opt/fzf/install"
if [ -f "$install" ] && ! [ -d "${XDG_CONFIG_HOME:-$HOME/.config}/fzf" ]; then
  "$install" --xdg --key-bindings --completion --no-update-rc
fi

# === gem ===

gem install mdl

# === npm ===

npm install -g \
  pyright \
  @elm-tooling/elm-language-server \
  @stoplight/spectral

# === pipx ===

for app in \
  flake8 \
  isort \
  pre-commit \
  git+git://github.com/psf/black; do
  pipx install "$app"
done
url=https://raw.githubusercontent.com/dycw/pre-commit-hooks/master/flake8-extensions
for extension in $(curl $url); do
  pipx inject flake8 "$extension"
done

# === ghcup ===

if ! command -v ghcup >/dev/null 2>&1; then
  curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
fi
cabal install brittany

# === poetry ===

if ! command -v poetry >/dev/null 2>&1; then
  url=https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
  curl -sSL $url | python -
fi

# === pyenv ===

if command -v pyenv >/dev/null 2>&1; then
  pyenv install -s 3.9.1
else
  echo "Expected to find pyenv; abort me..."
  sleep 999
fi

# === pynvim ===

brew_python="$(brew --prefix)/bin/python3"
pynvim="$XDG_CACHE_HOME/pynvim"
bin="$pynvim/bin"
if [ -f "$brew_python" ] && ! [ -f "$bin/python" ]; then
  mkdir -p "$pynvim"
  cd "$pynvim" || exit
  "$brew_python" -m venv .
  pip="$bin/pip"
  if [ -f "$pip" ]; then
    "$pip" install --upgrade pip
    "$pip" install neovim
  fi
fi

# === vim-plug ===

for directory in "$HOME/.vim" "${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site"; do
  plug_vim="$directory/autoload/plug.vim"
  if ! [ -f "$plug_vim" ]; then
    curl -fLo "$plug_vim" --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  fi
done

# === stack ===

if ! command -v stack >/dev/null 2>&1; then
  curl -sSL https://get.haskellstack.org/ | sh
fi

# === wally ===

sudo apt -y install libusb-dev
wally_rules=/etc/udev/rules.d/50-wally.rules
if ! [ -f "$wally_rules" ]; then
  sudo tee -a "$wally_rules" >/dev/null 2>&1 <<END
# Teensy rules for the Ergodox EZ
ATTRS{idVendor}=="16c0", ATTRS{idProduct}=="04[789B]?", ENV{ID_MM_DEVICE_IGNORE}="1"
ATTRS{idVendor}=="16c0", ATTRS{idProduct}=="04[789A]?", ENV{MTP_NO_PROBE}="1"
SUBSYSTEMS=="usb", ATTRS{idVendor}=="16c0", ATTRS{idProduct}=="04[789ABCD]?", MODE:="0666"
KERNEL=="ttyACM*", ATTRS{idVendor}=="16c0", ATTRS{idProduct}=="04[789B]?", MODE:="0666"

# STM32 rules for the Moonlander and Planck EZ
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="df11", \
    MODE:="0666", \
    SYMLINK+="stm32_dfu"
END
  cd /usr/local/bin || exit
  sudo wget https://configure.ergodox-ez.com/wally/linux -O wally
  sudo chmod +x wally
  sudo groupadd plugdev
  sudo usermod -aG plugdev "$USER"
fi

# === zsh & zinit ===

if (command -v zsh >/dev/null 2>&1) && ! (grep -q zsh "/etc/shells"); then
  command -v zsh | sudo tee -a /etc/shells
  sudo chsh -s "$(command -v zsh)" "${USER}"
fi
if ! [ -d "$HOME/.zinit" ]; then
  url=https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh
  curl -fsSL "$url"
fi

# === apt ===

for repo in aslatter/ppa linuxuprising/apps linuxgndu/sqlitebrowser; do
  sudo add-apt-repository -y "ppa:$repo"
done
sudo apt -y install \
  alacritty \
  pdfarranger \
  qutebrowser \
  sqlitebrowser \
  texlive-xetex \
  tmpreaper \
  vim \
  chrome-gnome-shell gnome-tweaks # screenshot locations

# === apt: nordvpn ===

if ! command -v nordvpn >/dev/null 2>&1; then
  curl -sSf https://downloads.nordcdn.com/apps/linux/install.sh
fi

# === snap ===

sudo snap install \
  insomnia-designer \
  signal-desktop \
  spotify

# === sound (https://intel.ly/3r68ua1) ===

alsa_base_conf=/etc/modprobe.d/alsa-base.conf
if [ -f "$alsa_base_conf" ]; then
  dell_headset_multi='options snd-hda-intel model=dell-headset-multi'
  if ! grep "$dell_headset_multi" "$alsa_base_conf" >/dev/null 2>&1; then
    echo "$dell_headset_multi" | sudo tee -a "$alsa_base_conf"
  fi
fi

# === SSH key ===

brew install xclip

config_local="${XDG_CONFIG_HOME:-$HOME/.config}/git/config.local"
if ! [ -f "$config_local" ]; then
  tee -a "$config_local" >/dev/null 2>&1 <<END
[user]
  name = Derek Wan
  email = d.wan@icloud.com
END
fi

private="$HOME/.ssh/id_rsa"
public="$private.pub"
if ! [ -f "$public" ]; then
  ssh-keygen -b 4096 -f "$private" -q -t rsa -C d.wan@icloud.com -N '' \
    <<<y >/dev/null 2>&1
  ssh-agent -s
  ssh-add
  xclip -sel clip <"$public"
  firefox "https://github.com/settings/keys"
  echo "Please add your SSH key (copied) to GitHub"
  cd "$PATH_DOTFILES" || exit
  git remote set-url origin git@github.com:dycw/dotfiles.git
fi
