#!/usr/bin/env bash

# git

if ! command -v git >/dev/null 2>&1; then
	sudo apt-get update
	sudo apt-get --yes install git
fi

# git config

path="$HOME/.config/git/config.local"
if ! [ -f "$path" ]; then
	{
		printf "[user]\n"
		printf "\tname = Derek Wan\n"
		printf "\temail = d.wan@icloud.com\n"
	} >>"$path"
fi

# SSH key

private="$HOME/.ssh/id_rsa"
public="$private.pub"
if ! [ -f "$public" ]; then
	ssh-keygen -t rsa -b 4096 -C "d.wan@icloud.com"
	ssh-agent -s
	ssh-add -K "$private"
fi

# clone repo

root="$HOME/.dotfiles"
if ! [ -d "$root" ]; then
	while true; do
		read -e -r -n1 -p "Is your SSH key already added to Github? (y/n)? " input
		if [ "$input" = "y" ]; then
			break
		fi

		name=xclip
		if ! command -v "$name" >/dev/null 2>&1; then
			sudo apt-get --yes install "$name"
		fi

		echo "Please add your SSH key (copied) to Github at:"
		echo "    https://github.com/settings/keys"
		xclip -sel clip <"$public"
	done
	git clone --recurse-submodules git@github.com:dycw/dotfiles.git "$root"
fi

# symlinks

process_link() {
	file="$1"
	link="${2/#\~/$HOME}"
	if [ -L "$link" ]; then
		old=$(readlink "$link")
		if [ "$old" != "$file" ]; then
			echo "Re-directing symlink:"
			echo "       $link"
			echo "old -> $old"
			echo "new -> $file"
			rm "$link"
			make_link "$file" "$link"
		fi
	else
		echo "Making symlink:"
		echo "   $link"
		echo "-> $file"
		make_link "$file" "$link"
	fi
}

make_link() {
	file="$1"
	link="$2"
	mkdir -p "$(dirname "$link")"
	ln -s "$file" "$link"
}

mapfile -t files < <(find "$root" -name "*.symlink*" -type f)
for file in "${files[@]}"; do
	mapfile -t matches < <(grep "symlink=" "$file")
	for match in "${matches[@]}"; do
		mapfile -td = splits < <(printf "%s" "$match")
		link=${splits[1]}
		process_link "$file" "$link"
	done
done

# installers

mapfile -t files < <(find "$root" -name "install.sh" -type f)
for file in "${files[@]}"; do
	# shellcheck source=/dev/null
	source "$file"
done
