#!/usr/bin/env bash

# === brew ===

ensure_apt_install() {
	pkg="$1"
	repo="$2"
	if ! dpkg -s "$pkg" >/dev/null 2>&1; then
		if [ -n "$repo" ]; then
			sudo add-apt-repository -y "$repo"
		fi
		sudo apt update
		sudo apt -y install "$pkg"
	fi
}

ensure_apt_install curl
ensure_apt_install git

if ! command -v brew >/dev/null 2>&1; then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# === symlinks ===

make_link() {
	file="$1"
	link="$2"
	mkdir -p "$(dirname "$link")"
	ln -s "$file" "$link"
}

process_link() {
	file="$1"
	link="$2"
	if [ -f "$link" ]; then
		if [ -L "$link" ]; then
			old="$(readlink "$link")"
			if [ "$old" != "$file" ]; then
				echo "\
Re-directing symlink:
       $link
old -> $old
new -> $file"
				rm "$link"
				make_link "$file" "$link"
			fi
		else
			backup="$link.bk"
			echo "\
Backing up existing file, and then overriding with symlink:
       $link
old -> $backup
new -> $file"
			mv "$link" "$backup"
			make_link "$file" "$link"
		fi
	else
		echo "\
Making symlink:
   $link
-> $file"
		make_link "$file" "$link"
	fi
}

dotfiles="$HOME/dotfiles"
if ! [ -d "$dotfiles" ]; then
	git clone https://github.com/dycw/dotfiles.git "$dotfiles"
fi

home="$HOME/dotfiles/home"
mapfile -t dotfiles < <(find "$home" -type f -or -type l)
for dotfile in "${dotfiles[@]}"; do
	file="$(realpath "$dotfile")"
	if [ -f "$file" ]; then
		link="$HOME/$(realpath --relative-to="$home" "$file")"
		process_link "$file" "$link"
	fi
done

process_link "$HOME/dotfiles/submodules/.tmux/.tmux.conf" "$HOME/.tmux.conf"

# === reboot, or brew post-installation ===

ensure_brew_install() {
	if ! brew list "$1" >/dev/null 2>&1; then
		brew install "$@"
	fi
}

if command -v brew >/dev/null 2>&1; then
	ensure_apt_install build-essential
	ensure_brew_install gcc
else
	echo "Time to reboot"
	while true; do
		read -e -r -n1 -p "Reboot needed; press 'y' to confirm. " input
		if [ "$input" = "y" ]; then
			reboot
		else
			exit 0
		fi
	done
fi

# === SSH key ===

ensure_brew_install xclip

config="$HOME/.config/git/config.local"
if ! [ -f "$config" ]; then
	tee -a "$config" >/dev/null 2>&1 <<END
[user]
  name = Derek Wan
  email = d.wan@icloud.com
END
fi

private="$HOME/.ssh/id_rsa"
public="$private.pub"
if ! [ -f "$public" ]; then
	ssh-keygen -t rsa -b 4096 -C "d.wan@icloud.com"
	ssh-agent -s
	ssh-add -K "$private"
fi

marker="$HOME/.ssh/.added-to-github"
if ! [ -f "$marker" ]; then
	xclip -sel clip <"$public"
	firefox "https://github.com/settings/keys"
	while true; do
		read -e -r -n1 -p "Add your SSH key (copied) to GitHub; press 'y' when done. " input
		if [ "$input" = "y" ]; then
			touch "$marker"
			git remote set-url origin git@github.com:dycw/dotfiles.git
			break
		fi
	done
fi

# === brew installs ===

# need to make valid shell
#      command -v zsh | sudo tee -a /etc/shells
#      sudo chsh -s "$(command -v zsh)" "${USER}"

# start installing other things

ensure_brew_install bandwhich
ensure_brew_install bat
ensure_brew_install bingrep
ensure_brew_install broot
ensure_brew_install ddgr
ensure_brew_install direnv
ensure_brew_install diskonaut
ensure_brew_install dust
ensure_brew_install elm
ensure_brew_install exa
ensure_brew_install fd
ensure_brew_install fzf
ensure_brew_install git-crypt
ensure_brew_install git-delta
ensure_brew_install googler
ensure_brew_install grex
ensure_brew_install hyperfine
ensure_brew_install mdcat
ensure_brew_install neovim
ensure_brew_install node
ensure_brew_install procs
ensure_brew_install ripgrep
ensure_brew_install sd
ensure_brew_install speedtest-cli
ensure_brew_install spotify-tui
ensure_brew_install starship
ensure_brew_install tealdeer
ensure_brew_install tmux
ensure_brew_install tokei
ensure_brew_install tree
ensure_brew_install watchexec
ensure_brew_install zoxide
ensure_brew_install zsh
ensure_brew_install clementtsang/bottom/bottom
ensure_brew_install eth-p/software/bat-extras

# === fzf ===
fzf_bash="$XDG_CONFIG_HOME/fzf/fzf.bash"
if ! [ -f "$fzf_bash" ]; then
	"$(brew --prefix)/opt/fzf/install" --xdg --key-bindings --completion --no-update-rc
fi

# === cargo installs ===

ensure_cargo_install() {
	if ! command -v "$1" >/dev/null 2>&1; then
		cargo install "$1"
	fi
}

ensure_cargo_install gitui
ensure_cargo_install gitweb
ensure_cargo_install rmesg

# === conda ===

if ! command -v conda >/dev/null 2>&1; then
	miniconda="$(mktemp -d)/miniconda.sh"
	wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O "$miniconda"
	bash "$miniconda" -b -u -p ~/miniconda3
	"$HOME/miniconda3/bin/conda" init bash
	"$HOME/miniconda3/bin/conda" init zsh
fi

neovim_dir="$HOME/miniconda3/envs/neovim"
if ! [ -d "$neovim_dir" ]; then
	conda create -n neovim -c conda-forge python=3.9 pynvim
fi

# === curl ===
if ! command -v nordvpn >/dev/null 2>&1; then
	sh <(curl -sSf https://downloads.nordcdn.com/apps/linux/install.sh)
fi

plug_vim="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/autoload/plug.vim"
if ! [ -f "$plug_vim" ]; then
	sh -c 'curl -fLo "$plug_vim" --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
fi

if ! [ -d "$HOME/.zinit" ]; then
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)"
fi

# === apt ===

ensure_apt_install pdfarranger ppa:linuxuprisinig/apps
ensure_apt_install qutebrowser
ensure_apt_install sqlitebrowser ppa:linuxgndu/sqlitebrowser
ensure_apt_install texlive-xetex
ensure_apt_install chrome-gnome-shell # screenshot locations
ensure_apt_install gnome-tweaks       # screenshot locations

# === snap ===

ensure_snap_install() {
	pkg="$1"
	if ! command -v "$pkg" >/dev/null 2>&1; then
		shift
		sudo snap install "$pkg" "$@"
	fi
}

ensure_snap_install insomnia-designer
ensure_snap_install signal-desktop
# ensure_snap_install transmission --beta
