#!/usr/bin/env sh
# shellcheck source=/dev/null

echo_date() { echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"; }

use_uv_python() {
	activate='.venv/bin/activate'
	if [ -f "${activate}" ]; then
		. "${activate}"
	else
		uv venv
	fi
	uv sync
}

layout_uv() {
	if [ -d ".venv" ]; then
		VIRTUAL_ENV="$(pwd)/.venv"
	fi
	if [ -z "${VIRTUAL_ENV}" ] || [ ! -d "${VIRTUAL_ENV}" ]; then
		uv venv
		VIRTUAL_ENV="$(pwd)/.venv"
	fi
	PATH_add "${VIRTUAL_ENV}/bin"
	export UV_ACTIVE=1
	export VIRTUAL_ENV
}
