#!/usr/bin/env sh
# shellcheck source=/dev/null

use_uv_python() {
	source_up_if_exists
	dotenv_if_exists
	source_env_if_exists .envrc.local
	activate='.venv/bin/activate'
	if [ -f "${activate}" ]; then
		. "${activate}"
	else
		uv venv
	fi
	repo_root="$(git rev-parse --show-toplevel)"
	script="${repo_root}/scripts/uv-sync.sh"
	if [ -f "${script}" ]; then
		. "${script}"
	else
		uv sync
	fi
}
