#!/usr/bin/env sh
# shellcheck source=/dev/null

echo_date() { echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"; }

use_uv_python() {
	activate='.venv/bin/activate'
	if ! [ -f "${activate}" ]; then
		uv venv
	fi
	. "${activate}"
	uv sync --all-extras --active --locked
}
use_uv_python
