#!/usr/bin/env zsh
# shellcheck disable=SC1090,SC1091

#### interactive only #########################################################
#
if ! [[ -o interactive ]]; then
    return
fi

#### common POSIX #############################################################
#
setopt NULL_GLOB
for file in "${HOME}"/.config/posix/*.sh; do
    # restore original settings since 'set -u' (nounset) can brick /etc/profile.d/*
    current="$(set +o)"
    if [ -f "${file}" ]; then
        . "${file}"
    fi
    eval "${current}"
    unset current
done
unsetopt NULL_GLOB
