[ai]
rules = ""

[completion]
activate_on_typing = true
copilot = false

[diagnostics]

[display]
cell_output = "above"
code_editor_font_size = 14
dataframes = "rich"
default_table_page_size = 10
default_width = "medium"
theme = "light"

[experimental]

[formatting]
line_length = 79

[keymap]
preset = "default"

[keymap.overrides]
"cell.createAbove" = "Cmd-k"
"cell.createBelow" = "Cmd-j"
"cell.focusDown" = "Ctrl-j"
"cell.focusUp" = "Ctrl-k"
"cell.format" = "Ctrl-f"
"cell.goToDefinition" = "Ctrl-d"
"cell.run" = "Ctrl-enter"
"cell.runAndNewAbove" = "Ctrl-Shift-enter"
"global.focusBottom" = "Ctrl-Shift-j"
"global.focusTop" = "Ctrl-Shift-k"
"global.interrupt" = "Ctrl-i"
"global.toggleSidebar" = "Ctrl-h"

[language_servers.pylsp]
enable_flake8 = false
enable_mypy = true
enable_pydocstyle = false
enable_pyflakes = false
enable_pylint = false
enable_ruff = true
enabled = true

[package_management]
manager = "uv"

[runtime]
auto_instantiate = true
auto_reload = "off"
default_sql_output = "auto"
on_cell_change = "autorun"
output_max_bytes = 8000000
reactive_tests = true
std_stream_max_bytes = 1000000
watcher_on_save = "lazy"

[save]
autosave = "after_delay"
autosave_delay = 1000
format_on_save = true

[server]
browser = "default"
follow_symlink = false

[snippets]
custom_paths = []
include_default_snippets = true
