services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: ${TAILSCALE_HOSTNAME:?}
    restart: always
    environment:
      - TS_AUTHKEY=file:/run/secrets/auth_key.txt
      - TS_EXTRA_ARGS=--login-server=${TAILSCALE_LOGIN_SERVER:?} --accept-routes
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
    secrets:
      - auth_key.txt
    volumes:
      - tailscale-state:/var/lib/tailscale

secrets:
  auth_key.txt:
    file: ${TAILSCALE_AUTH_KEY:?}

volumes:
  tailscale-state:
