set dotenv-load := true
set positional-arguments := true

# up/down

@up:
  tailscale up --accept-dns --accept-routes \
    --auth-key "file:${TAILSCALE_AUTH_KEY:?}" --force-reauth \
    --hostname "${TAILSCALE_HOSTNAME:?}" \
    --login-server ${TAILSCALE_LOGIN_SERVER:?} --reset

@down:
  tailscale down

@restart:
  just down && just upd

# exit node

@exit-node:
  tailscale set --exit-node=qrt-nanode

@no-exit-node:
  tailscale set --exit-node=

# status

@status:
  tailscale status

@watch-status:
  watch -n1 -- tailscale status
