#!/usr/bin/env bash
# shellcheck disable=SC1090,SC1091

# System profile
if [ -d /etc/profile.d ]; then
	for _f in /etc/profile.d/*.sh; do
		[ -r "${_f}" ] && . "${_f}"
	done
	unset _f
fi

# User profile (environment variables)
for _f in "${HOME}"/.bash_profile.d/*.sh; do
	[ -r "${_f}" ] && [ -f "${_f}" ] && . "${_f}"
done
unset _f

# Interactive shell
if [ -f "${HOME}/.bashrc" ]; then
	. "${HOME}/.bashrc"
fi
