set dotenv-load := true
set positional-arguments := true

# up/down

@logs:
  docker logs --follow tailscale

@up:
  docker compose up

@upd:
  docker compose up --detach

@down:
  docker compose down

@restart:
  just down && just upd

# status

@status:
  docker exec -i tailscale tailscale status
