#!/usr/bin/env bash
# shellcheck source=/dev/null

_script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
_env="$_script_dir/.env"

if [ -f "$_env" ]; then
	echo "[$(date +'%Y-%m-%d %H:%M:%S')] Sourcing environment file '$_env'..."
	source "$_env"

	declare -a _paths=("$HOME"/Dropbox "$HOME"/work)
	for _path in "${_paths[@]}"; do
		if [ -d "$_path" ]; then
			echo "[$(date +'%Y-%m-%d %H:%M:%S')] Backing up '$_path'..."
			restic backup "$_path"
		else
			echo "[$(date +'%Y-%m-%d %H:%M:%S')] Unable to find '$_path'; skipping..."
		fi
	done
else
	echo "[$(date +'%Y-%m-%d %H:%M:%S')] Unable to find environment file '$_env'; exiting..."
fi
