#!/usr/bin/env sh
# shellcheck disable=SC1090

set -eu

#### env ######################################################################

script_dir=$(dirname -- "$(realpath -- "$0")")
env="${script_dir}/.env"

if ! [ -r "${env}" ]; then
	echo "[$(date '+%Y-%m-%d %H:%M:%S')] Unable to find environment file '${env}'; exiting..." >&2
	exit 1
fi

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Sourcing '${env}'..."
. "${env}"

#### backup ###################################################################

for p in \
	"${HOME}/Dropbox" \
	"${HOME}/personal" \
	"${HOME}/work"; do
	if [ -d "${p}" ]; then
		echo "[$(date '+%Y-%m-%d %H:%M:%S')] Backing up '${p}'..."
		restic backup --exclude .venv "${p}"
	else
		echo "[$(date '+%Y-%m-%d %H:%M:%S')] Unable to find '${p}'; skipping..." >&2
	fi
done

#### forget ###################################################################

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Forgetting & pruning..."
restic forget --keep-within-hourly 7d --keep-within-daily 1m \
	--keep-within-weekly 1y --keep-within-monthly 5y \
	--keep-within-yearly 10y --prune --repack-small \
	--repack-uncompressed
