#!/usr/bin/env bash
# shellcheck source=/dev/null

_script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
_env="$_script_dir/.env"

if [ -f "$_env" ]; then
	echo "Sourcing environment file '$_env'..."
	source "$_env"

	declare -a _paths=("$PATH_DROPBOX" "$HOME"/work)
	for _path in "${_paths[@]}"; do
		if [ -d "$_path" ]; then
			echo "Backing up '$_path'..."
			restic backup "$_path"
		else
			echo "Unable to find '$_path'; skipping..."
		fi
	done
else
	echo "Unable to find environment file '$_env'; exiting..."
fi
