#!/usr/bin/env bash
# shellcheck source=/dev/null

_script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
_env="${_script_dir}/.env"
echo_date() { echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"; }

if [ -f "$_env" ]; then
	echo_date "Sourcing environment file '$_env'..."
	source "$_env"
	restic -r "$RESTIC_REPOSITORY" init
else
	echo_date "Unable to find environment file '$_env'; exiting..."
fi
