# ---- llm ----
model: qrt-gpt:qwen3-coder:30b

# ---- behavior ----
keybindings: vi
editor: nvim

# ---- prelude ----
repl_prelude: role:%code%
cmd_prelude: role:%code%

# ---- session ----
save_session: true

# ---- clients ----
clients:
  - type: openai-compatible
    name: qrt-gpt
    api_base: http://???.???.???.???:???/v1
    models:
      - name: gpt-oss:20b
  - type: openai-compatible
    name: qrt-qwen3
    api_base: http://???.???.???.???:???/v1
    models:
      - name: qwen3-coder:30b
