# ---- llm ----
model: gpt:gpt-oss

# ---- behavior ----
keybindings: vi
editor: nvim

# ---- prelude ----
repl_prelude: role:general
cmd_prelude: role:general

# ---- session ----
save_session: true

# ---- clients ----
clients:
  - name: gpt
    type: openai-compatible
    api_base: http://???.???.???.???:???/v1 # Ollama
    models:
      - name: gpt-oss:20b
  - name: qwen30b
    type: openai-compatible
    api_base: http://???.???.???.???:???/v1 # Ollama
    models:
      - name: qwen3-coder:30b
  - name: qwen7b
    type: openai-compatible
    api_base: http://???.???.???.???:???/v1 # Ollama
    models:
      - name: qwen2.5-coder:7b
  - name: qwen3-coder-30b-moe-4bit
    type: openai-compatible
    api_base: http://???.???.???.???:???/v1 # LM studio
    models:
      - name: bbecedefd826819d2c6b6465e88ca7b9b8ad3407
  - name: qwen3-coder-30b-moe-8bit
    type: openai-compatible
    api_base: http://???.???.???.???:???/v1 # LM studio
    models:
      - name: 4285def38c15e8a2a01bf136a1a2349484003540
