# ---- llm ----
model: gpt:gpt-oss

# ---- behavior ----
keybindings: vi
editor: nvim

# ---- prelude ----
repl_prelude: role:general
cmd_prelude: role:general

# ---- session ----
save_session: true

# ---- clients ----
clients:
  - name: gpt
    type: openai-compatible
    api_base: http://???.???.???.???:???/v1
  - name: qwen30b
    type: openai-compatible
    api_base: http://???.???.???.???:???/v1
  - name: qwen30bmlx
    type: openai-compatible
    api_base: http://???.???.???.???:???/v1
  - name: qwen7b
    type: openai-compatible
    api_base: http://???.???.???.???:???/v1
