# ---- llm ----
model: qrt-ollama:qwen3-coder:30b

# ---- behavior ----
keybindings: vi
editor: nvim

# ---- prelude ----
repl_prelude: session:work

# ---- session ----
save_session: true

# ---- clients ----
clients:
  - type: openai-compatible
    name: qrt-ollama
    api_base: http://???.???.???.???:???/v1
    models:
      - name: qwen3-coder:30b
