# ---- llm ----
model: gpt:gpt-oss

# ---- behavior ----
keybindings: vi
editor: nvim

# ---- prelude ----
repl_prelude: role:general
cmd_prelude: role:general

# ---- session ----
save_session: true

# ---- clients ----
clients:
  - name: gpt
    type: openai-compatible
    api_base: http://???.???.???.???:???/v1
    models:
      - name: gpt-oss:20b
  - name: qwen30b
    type: openai-compatible
    api_base: http://???.???.???.???:???/v1
    models:
      - name: qwen3-coder:30b
  - name: qwen14b
    type: openai-compatible
    api_base: http://???.???.???.???:???/v1
    models:
      - name: qwen2.5-coder:14b
  - name: qwen7b
    type: openai-compatible
    api_base: http://???.???.???.???:???/v1
    models:
      - name: qwen2.5-coder:7b
