#!/usr/bin/env bash
alias pyt='pytest -ra -vv --color=yes --strict-markers'
alias pytc='pytest -ra -vv --color=yes --strict-markers --no-cov'
alias pytcf='pytest -ra -vv --color=yes --strict-markers --no-cov -f'
alias pytcfi='pytest -ra -vv --color=yes --strict-markers --no-cov -f --instafail'
alias pytcfik='pytest -ra -vv --color=yes --strict-markers --no-cov -f --instafail --randomly-dont-reorganize -k'
alias pytcfim='pytest -ra -vv --color=yes --strict-markers --no-cov -f --instafail --randomly-dont-reorganize --maxfail'
alias pytcfin='pytest -ra -vv --color=yes --strict-markers --no-cov -f --instafail -nauto'
alias pytcfink='pytest -ra -vv --color=yes --strict-markers --no-cov -f --instafail -nauto --randomly-dont-reorganize -k'
alias pytcfinm='pytest -ra -vv --color=yes --strict-markers --no-cov -f --instafail -nauto --randomly-dont-reorganize --maxfail'
alias pytcfk='pytest -ra -vv --color=yes --strict-markers --no-cov -f --randomly-dont-reorganize -k'
alias pytcfm='pytest -ra -vv --color=yes --strict-markers --no-cov -f --randomly-dont-reorganize --maxfail'
alias pytcfn='pytest -ra -vv --color=yes --strict-markers --no-cov -f -nauto'
alias pytcfni='pytest -ra -vv --color=yes --strict-markers --no-cov -f -nauto --instafail'
alias pytcfnik='pytest -ra -vv --color=yes --strict-markers --no-cov -f -nauto --instafail --randomly-dont-reorganize -k'
alias pytcfnim='pytest -ra -vv --color=yes --strict-markers --no-cov -f -nauto --instafail --randomly-dont-reorganize --maxfail'
alias pytcfnk='pytest -ra -vv --color=yes --strict-markers --no-cov -f -nauto --randomly-dont-reorganize -k'
alias pytcfnm='pytest -ra -vv --color=yes --strict-markers --no-cov -f -nauto --randomly-dont-reorganize --maxfail'
alias pytcfnx='pytest -ra -vv --color=yes --strict-markers --no-cov -f -nauto --randomly-dont-reorganize -x'
alias pytcfnxk='pytest -ra -vv --color=yes --strict-markers --no-cov -f -nauto --randomly-dont-reorganize -x --randomly-dont-reorganize -k'
alias pytcfx='pytest -ra -vv --color=yes --strict-markers --no-cov -f --randomly-dont-reorganize -x'
alias pytcfxk='pytest -ra -vv --color=yes --strict-markers --no-cov -f --randomly-dont-reorganize -x --randomly-dont-reorganize -k'
alias pytcfxn='pytest -ra -vv --color=yes --strict-markers --no-cov -f --randomly-dont-reorganize -x -nauto'
alias pytcfxnk='pytest -ra -vv --color=yes --strict-markers --no-cov -f --randomly-dont-reorganize -x -nauto --randomly-dont-reorganize -k'
alias pytci='pytest -ra -vv --color=yes --strict-markers --no-cov --instafail'
alias pytcif='pytest -ra -vv --color=yes --strict-markers --no-cov --instafail -f'
alias pytcifk='pytest -ra -vv --color=yes --strict-markers --no-cov --instafail -f --randomly-dont-reorganize -k'
alias pytcifm='pytest -ra -vv --color=yes --strict-markers --no-cov --instafail -f --randomly-dont-reorganize --maxfail'
alias pytcifn='pytest -ra -vv --color=yes --strict-markers --no-cov --instafail -f -nauto'
alias pytcifnk='pytest -ra -vv --color=yes --strict-markers --no-cov --instafail -f -nauto --randomly-dont-reorganize -k'
alias pytcifnm='pytest -ra -vv --color=yes --strict-markers --no-cov --instafail -f -nauto --randomly-dont-reorganize --maxfail'
alias pytcik='pytest -ra -vv --color=yes --strict-markers --no-cov --instafail --randomly-dont-reorganize -k'
alias pytcim='pytest -ra -vv --color=yes --strict-markers --no-cov --instafail --randomly-dont-reorganize --maxfail'
alias pytcin='pytest -ra -vv --color=yes --strict-markers --no-cov --instafail -nauto'
alias pytcinf='pytest -ra -vv --color=yes --strict-markers --no-cov --instafail -nauto -f'
alias pytcinfk='pytest -ra -vv --color=yes --strict-markers --no-cov --instafail -nauto -f --randomly-dont-reorganize -k'
alias pytcinfm='pytest -ra -vv --color=yes --strict-markers --no-cov --instafail -nauto -f --randomly-dont-reorganize --maxfail'
alias pytcink='pytest -ra -vv --color=yes --strict-markers --no-cov --instafail -nauto --randomly-dont-reorganize -k'
alias pytcinm='pytest -ra -vv --color=yes --strict-markers --no-cov --instafail -nauto --randomly-dont-reorganize --maxfail'
alias pytck='pytest -ra -vv --color=yes --strict-markers --no-cov --randomly-dont-reorganize -k'
alias pytcm='pytest -ra -vv --color=yes --strict-markers --no-cov --randomly-dont-reorganize --maxfail'
alias pytcn='pytest -ra -vv --color=yes --strict-markers --no-cov -nauto'
alias pytcnf='pytest -ra -vv --color=yes --strict-markers --no-cov -nauto -f'
alias pytcnfi='pytest -ra -vv --color=yes --strict-markers --no-cov -nauto -f --instafail'
alias pytcnfik='pytest -ra -vv --color=yes --strict-markers --no-cov -nauto -f --instafail --randomly-dont-reorganize -k'
alias pytcnfim='pytest -ra -vv --color=yes --strict-markers --no-cov -nauto -f --instafail --randomly-dont-reorganize --maxfail'
alias pytcnfk='pytest -ra -vv --color=yes --strict-markers --no-cov -nauto -f --randomly-dont-reorganize -k'
alias pytcnfm='pytest -ra -vv --color=yes --strict-markers --no-cov -nauto -f --randomly-dont-reorganize --maxfail'
alias pytcnfx='pytest -ra -vv --color=yes --strict-markers --no-cov -nauto -f --randomly-dont-reorganize -x'
alias pytcnfxk='pytest -ra -vv --color=yes --strict-markers --no-cov -nauto -f --randomly-dont-reorganize -x --randomly-dont-reorganize -k'
alias pytcni='pytest -ra -vv --color=yes --strict-markers --no-cov -nauto --instafail'
alias pytcnif='pytest -ra -vv --color=yes --strict-markers --no-cov -nauto --instafail -f'
alias pytcnifk='pytest -ra -vv --color=yes --strict-markers --no-cov -nauto --instafail -f --randomly-dont-reorganize -k'
alias pytcnifm='pytest -ra -vv --color=yes --strict-markers --no-cov -nauto --instafail -f --randomly-dont-reorganize --maxfail'
alias pytcnik='pytest -ra -vv --color=yes --strict-markers --no-cov -nauto --instafail --randomly-dont-reorganize -k'
alias pytcnim='pytest -ra -vv --color=yes --strict-markers --no-cov -nauto --instafail --randomly-dont-reorganize --maxfail'
alias pytcnk='pytest -ra -vv --color=yes --strict-markers --no-cov -nauto --randomly-dont-reorganize -k'
alias pytcnm='pytest -ra -vv --color=yes --strict-markers --no-cov -nauto --randomly-dont-reorganize --maxfail'
alias pytcnx='pytest -ra -vv --color=yes --strict-markers --no-cov -nauto --randomly-dont-reorganize -x'
alias pytcnxf='pytest -ra -vv --color=yes --strict-markers --no-cov -nauto --randomly-dont-reorganize -x -f'
alias pytcnxfk='pytest -ra -vv --color=yes --strict-markers --no-cov -nauto --randomly-dont-reorganize -x -f --randomly-dont-reorganize -k'
alias pytcnxk='pytest -ra -vv --color=yes --strict-markers --no-cov -nauto --randomly-dont-reorganize -x --randomly-dont-reorganize -k'
alias pytcp='pytest -ra -vv --color=yes --strict-markers --no-cov --randomly-dont-reorganize --pdb'
alias pytcpk='pytest -ra -vv --color=yes --strict-markers --no-cov --randomly-dont-reorganize --pdb --randomly-dont-reorganize -k'
alias pytcpm='pytest -ra -vv --color=yes --strict-markers --no-cov --randomly-dont-reorganize --pdb --randomly-dont-reorganize --maxfail'
alias pytcpx='pytest -ra -vv --color=yes --strict-markers --no-cov --randomly-dont-reorganize --pdb --randomly-dont-reorganize -x'
alias pytcpxk='pytest -ra -vv --color=yes --strict-markers --no-cov --randomly-dont-reorganize --pdb --randomly-dont-reorganize -x --randomly-dont-reorganize -k'
alias pytcx='pytest -ra -vv --color=yes --strict-markers --no-cov --randomly-dont-reorganize -x'
alias pytcxf='pytest -ra -vv --color=yes --strict-markers --no-cov --randomly-dont-reorganize -x -f'
alias pytcxfk='pytest -ra -vv --color=yes --strict-markers --no-cov --randomly-dont-reorganize -x -f --randomly-dont-reorganize -k'
alias pytcxfn='pytest -ra -vv --color=yes --strict-markers --no-cov --randomly-dont-reorganize -x -f -nauto'
alias pytcxfnk='pytest -ra -vv --color=yes --strict-markers --no-cov --randomly-dont-reorganize -x -f -nauto --randomly-dont-reorganize -k'
alias pytcxk='pytest -ra -vv --color=yes --strict-markers --no-cov --randomly-dont-reorganize -x --randomly-dont-reorganize -k'
alias pytcxn='pytest -ra -vv --color=yes --strict-markers --no-cov --randomly-dont-reorganize -x -nauto'
alias pytcxnf='pytest -ra -vv --color=yes --strict-markers --no-cov --randomly-dont-reorganize -x -nauto -f'
alias pytcxnfk='pytest -ra -vv --color=yes --strict-markers --no-cov --randomly-dont-reorganize -x -nauto -f --randomly-dont-reorganize -k'
alias pytcxnk='pytest -ra -vv --color=yes --strict-markers --no-cov --randomly-dont-reorganize -x -nauto --randomly-dont-reorganize -k'
alias pytcxp='pytest -ra -vv --color=yes --strict-markers --no-cov --randomly-dont-reorganize -x --randomly-dont-reorganize --pdb'
alias pytcxpk='pytest -ra -vv --color=yes --strict-markers --no-cov --randomly-dont-reorganize -x --randomly-dont-reorganize --pdb --randomly-dont-reorganize -k'
alias pytf='pytest -ra -vv --color=yes --strict-markers -f'
alias pytfc='pytest -ra -vv --color=yes --strict-markers -f --no-cov'
alias pytfci='pytest -ra -vv --color=yes --strict-markers -f --no-cov --instafail'
alias pytfcik='pytest -ra -vv --color=yes --strict-markers -f --no-cov --instafail --randomly-dont-reorganize -k'
alias pytfcim='pytest -ra -vv --color=yes --strict-markers -f --no-cov --instafail --randomly-dont-reorganize --maxfail'
alias pytfcin='pytest -ra -vv --color=yes --strict-markers -f --no-cov --instafail -nauto'
alias pytfcink='pytest -ra -vv --color=yes --strict-markers -f --no-cov --instafail -nauto --randomly-dont-reorganize -k'
alias pytfcinm='pytest -ra -vv --color=yes --strict-markers -f --no-cov --instafail -nauto --randomly-dont-reorganize --maxfail'
alias pytfck='pytest -ra -vv --color=yes --strict-markers -f --no-cov --randomly-dont-reorganize -k'
alias pytfcm='pytest -ra -vv --color=yes --strict-markers -f --no-cov --randomly-dont-reorganize --maxfail'
alias pytfcn='pytest -ra -vv --color=yes --strict-markers -f --no-cov -nauto'
alias pytfcni='pytest -ra -vv --color=yes --strict-markers -f --no-cov -nauto --instafail'
alias pytfcnik='pytest -ra -vv --color=yes --strict-markers -f --no-cov -nauto --instafail --randomly-dont-reorganize -k'
alias pytfcnim='pytest -ra -vv --color=yes --strict-markers -f --no-cov -nauto --instafail --randomly-dont-reorganize --maxfail'
alias pytfcnk='pytest -ra -vv --color=yes --strict-markers -f --no-cov -nauto --randomly-dont-reorganize -k'
alias pytfcnm='pytest -ra -vv --color=yes --strict-markers -f --no-cov -nauto --randomly-dont-reorganize --maxfail'
alias pytfcnx='pytest -ra -vv --color=yes --strict-markers -f --no-cov -nauto --randomly-dont-reorganize -x'
alias pytfcnxk='pytest -ra -vv --color=yes --strict-markers -f --no-cov -nauto --randomly-dont-reorganize -x --randomly-dont-reorganize -k'
alias pytfcx='pytest -ra -vv --color=yes --strict-markers -f --no-cov --randomly-dont-reorganize -x'
alias pytfcxk='pytest -ra -vv --color=yes --strict-markers -f --no-cov --randomly-dont-reorganize -x --randomly-dont-reorganize -k'
alias pytfcxn='pytest -ra -vv --color=yes --strict-markers -f --no-cov --randomly-dont-reorganize -x -nauto'
alias pytfcxnk='pytest -ra -vv --color=yes --strict-markers -f --no-cov --randomly-dont-reorganize -x -nauto --randomly-dont-reorganize -k'
alias pytfi='pytest -ra -vv --color=yes --strict-markers -f --instafail'
alias pytfic='pytest -ra -vv --color=yes --strict-markers -f --instafail --no-cov'
alias pytfick='pytest -ra -vv --color=yes --strict-markers -f --instafail --no-cov --randomly-dont-reorganize -k'
alias pytficm='pytest -ra -vv --color=yes --strict-markers -f --instafail --no-cov --randomly-dont-reorganize --maxfail'
alias pytficn='pytest -ra -vv --color=yes --strict-markers -f --instafail --no-cov -nauto'
alias pytficnk='pytest -ra -vv --color=yes --strict-markers -f --instafail --no-cov -nauto --randomly-dont-reorganize -k'
alias pytficnm='pytest -ra -vv --color=yes --strict-markers -f --instafail --no-cov -nauto --randomly-dont-reorganize --maxfail'
alias pytfik='pytest -ra -vv --color=yes --strict-markers -f --instafail --randomly-dont-reorganize -k'
alias pytfim='pytest -ra -vv --color=yes --strict-markers -f --instafail --randomly-dont-reorganize --maxfail'
alias pytfin='pytest -ra -vv --color=yes --strict-markers -f --instafail -nauto'
alias pytfinc='pytest -ra -vv --color=yes --strict-markers -f --instafail -nauto --no-cov'
alias pytfinck='pytest -ra -vv --color=yes --strict-markers -f --instafail -nauto --no-cov --randomly-dont-reorganize -k'
alias pytfincm='pytest -ra -vv --color=yes --strict-markers -f --instafail -nauto --no-cov --randomly-dont-reorganize --maxfail'
alias pytfink='pytest -ra -vv --color=yes --strict-markers -f --instafail -nauto --randomly-dont-reorganize -k'
alias pytfinm='pytest -ra -vv --color=yes --strict-markers -f --instafail -nauto --randomly-dont-reorganize --maxfail'
alias pytfk='pytest -ra -vv --color=yes --strict-markers -f --randomly-dont-reorganize -k'
alias pytfm='pytest -ra -vv --color=yes --strict-markers -f --randomly-dont-reorganize --maxfail'
alias pytfn='pytest -ra -vv --color=yes --strict-markers -f -nauto'
alias pytfnc='pytest -ra -vv --color=yes --strict-markers -f -nauto --no-cov'
alias pytfnci='pytest -ra -vv --color=yes --strict-markers -f -nauto --no-cov --instafail'
alias pytfncik='pytest -ra -vv --color=yes --strict-markers -f -nauto --no-cov --instafail --randomly-dont-reorganize -k'
alias pytfncim='pytest -ra -vv --color=yes --strict-markers -f -nauto --no-cov --instafail --randomly-dont-reorganize --maxfail'
alias pytfnck='pytest -ra -vv --color=yes --strict-markers -f -nauto --no-cov --randomly-dont-reorganize -k'
alias pytfncm='pytest -ra -vv --color=yes --strict-markers -f -nauto --no-cov --randomly-dont-reorganize --maxfail'
alias pytfncx='pytest -ra -vv --color=yes --strict-markers -f -nauto --no-cov --randomly-dont-reorganize -x'
alias pytfncxk='pytest -ra -vv --color=yes --strict-markers -f -nauto --no-cov --randomly-dont-reorganize -x --randomly-dont-reorganize -k'
alias pytfni='pytest -ra -vv --color=yes --strict-markers -f -nauto --instafail'
alias pytfnic='pytest -ra -vv --color=yes --strict-markers -f -nauto --instafail --no-cov'
alias pytfnick='pytest -ra -vv --color=yes --strict-markers -f -nauto --instafail --no-cov --randomly-dont-reorganize -k'
alias pytfnicm='pytest -ra -vv --color=yes --strict-markers -f -nauto --instafail --no-cov --randomly-dont-reorganize --maxfail'
alias pytfnik='pytest -ra -vv --color=yes --strict-markers -f -nauto --instafail --randomly-dont-reorganize -k'
alias pytfnim='pytest -ra -vv --color=yes --strict-markers -f -nauto --instafail --randomly-dont-reorganize --maxfail'
alias pytfnk='pytest -ra -vv --color=yes --strict-markers -f -nauto --randomly-dont-reorganize -k'
alias pytfnm='pytest -ra -vv --color=yes --strict-markers -f -nauto --randomly-dont-reorganize --maxfail'
alias pytfnx='pytest -ra -vv --color=yes --strict-markers -f -nauto --randomly-dont-reorganize -x'
alias pytfnxc='pytest -ra -vv --color=yes --strict-markers -f -nauto --randomly-dont-reorganize -x --no-cov'
alias pytfnxck='pytest -ra -vv --color=yes --strict-markers -f -nauto --randomly-dont-reorganize -x --no-cov --randomly-dont-reorganize -k'
alias pytfnxk='pytest -ra -vv --color=yes --strict-markers -f -nauto --randomly-dont-reorganize -x --randomly-dont-reorganize -k'
alias pytfx='pytest -ra -vv --color=yes --strict-markers -f --randomly-dont-reorganize -x'
alias pytfxc='pytest -ra -vv --color=yes --strict-markers -f --randomly-dont-reorganize -x --no-cov'
alias pytfxck='pytest -ra -vv --color=yes --strict-markers -f --randomly-dont-reorganize -x --no-cov --randomly-dont-reorganize -k'
alias pytfxcn='pytest -ra -vv --color=yes --strict-markers -f --randomly-dont-reorganize -x --no-cov -nauto'
alias pytfxcnk='pytest -ra -vv --color=yes --strict-markers -f --randomly-dont-reorganize -x --no-cov -nauto --randomly-dont-reorganize -k'
alias pytfxk='pytest -ra -vv --color=yes --strict-markers -f --randomly-dont-reorganize -x --randomly-dont-reorganize -k'
alias pytfxn='pytest -ra -vv --color=yes --strict-markers -f --randomly-dont-reorganize -x -nauto'
alias pytfxnc='pytest -ra -vv --color=yes --strict-markers -f --randomly-dont-reorganize -x -nauto --no-cov'
alias pytfxnck='pytest -ra -vv --color=yes --strict-markers -f --randomly-dont-reorganize -x -nauto --no-cov --randomly-dont-reorganize -k'
alias pytfxnk='pytest -ra -vv --color=yes --strict-markers -f --randomly-dont-reorganize -x -nauto --randomly-dont-reorganize -k'
alias pyti='pytest -ra -vv --color=yes --strict-markers --instafail'
alias pytic='pytest -ra -vv --color=yes --strict-markers --instafail --no-cov'
alias pyticf='pytest -ra -vv --color=yes --strict-markers --instafail --no-cov -f'
alias pyticfk='pytest -ra -vv --color=yes --strict-markers --instafail --no-cov -f --randomly-dont-reorganize -k'
alias pyticfm='pytest -ra -vv --color=yes --strict-markers --instafail --no-cov -f --randomly-dont-reorganize --maxfail'
alias pyticfn='pytest -ra -vv --color=yes --strict-markers --instafail --no-cov -f -nauto'
alias pyticfnk='pytest -ra -vv --color=yes --strict-markers --instafail --no-cov -f -nauto --randomly-dont-reorganize -k'
alias pyticfnm='pytest -ra -vv --color=yes --strict-markers --instafail --no-cov -f -nauto --randomly-dont-reorganize --maxfail'
alias pytick='pytest -ra -vv --color=yes --strict-markers --instafail --no-cov --randomly-dont-reorganize -k'
alias pyticm='pytest -ra -vv --color=yes --strict-markers --instafail --no-cov --randomly-dont-reorganize --maxfail'
alias pyticn='pytest -ra -vv --color=yes --strict-markers --instafail --no-cov -nauto'
alias pyticnf='pytest -ra -vv --color=yes --strict-markers --instafail --no-cov -nauto -f'
alias pyticnfk='pytest -ra -vv --color=yes --strict-markers --instafail --no-cov -nauto -f --randomly-dont-reorganize -k'
alias pyticnfm='pytest -ra -vv --color=yes --strict-markers --instafail --no-cov -nauto -f --randomly-dont-reorganize --maxfail'
alias pyticnk='pytest -ra -vv --color=yes --strict-markers --instafail --no-cov -nauto --randomly-dont-reorganize -k'
alias pyticnm='pytest -ra -vv --color=yes --strict-markers --instafail --no-cov -nauto --randomly-dont-reorganize --maxfail'
alias pytif='pytest -ra -vv --color=yes --strict-markers --instafail -f'
alias pytifc='pytest -ra -vv --color=yes --strict-markers --instafail -f --no-cov'
alias pytifck='pytest -ra -vv --color=yes --strict-markers --instafail -f --no-cov --randomly-dont-reorganize -k'
alias pytifcm='pytest -ra -vv --color=yes --strict-markers --instafail -f --no-cov --randomly-dont-reorganize --maxfail'
alias pytifcn='pytest -ra -vv --color=yes --strict-markers --instafail -f --no-cov -nauto'
alias pytifcnk='pytest -ra -vv --color=yes --strict-markers --instafail -f --no-cov -nauto --randomly-dont-reorganize -k'
alias pytifcnm='pytest -ra -vv --color=yes --strict-markers --instafail -f --no-cov -nauto --randomly-dont-reorganize --maxfail'
alias pytifk='pytest -ra -vv --color=yes --strict-markers --instafail -f --randomly-dont-reorganize -k'
alias pytifm='pytest -ra -vv --color=yes --strict-markers --instafail -f --randomly-dont-reorganize --maxfail'
alias pytifn='pytest -ra -vv --color=yes --strict-markers --instafail -f -nauto'
alias pytifnc='pytest -ra -vv --color=yes --strict-markers --instafail -f -nauto --no-cov'
alias pytifnck='pytest -ra -vv --color=yes --strict-markers --instafail -f -nauto --no-cov --randomly-dont-reorganize -k'
alias pytifncm='pytest -ra -vv --color=yes --strict-markers --instafail -f -nauto --no-cov --randomly-dont-reorganize --maxfail'
alias pytifnk='pytest -ra -vv --color=yes --strict-markers --instafail -f -nauto --randomly-dont-reorganize -k'
alias pytifnm='pytest -ra -vv --color=yes --strict-markers --instafail -f -nauto --randomly-dont-reorganize --maxfail'
alias pytik='pytest -ra -vv --color=yes --strict-markers --instafail --randomly-dont-reorganize -k'
alias pytim='pytest -ra -vv --color=yes --strict-markers --instafail --randomly-dont-reorganize --maxfail'
alias pytin='pytest -ra -vv --color=yes --strict-markers --instafail -nauto'
alias pytinc='pytest -ra -vv --color=yes --strict-markers --instafail -nauto --no-cov'
alias pytincf='pytest -ra -vv --color=yes --strict-markers --instafail -nauto --no-cov -f'
alias pytincfk='pytest -ra -vv --color=yes --strict-markers --instafail -nauto --no-cov -f --randomly-dont-reorganize -k'
alias pytincfm='pytest -ra -vv --color=yes --strict-markers --instafail -nauto --no-cov -f --randomly-dont-reorganize --maxfail'
alias pytinck='pytest -ra -vv --color=yes --strict-markers --instafail -nauto --no-cov --randomly-dont-reorganize -k'
alias pytincm='pytest -ra -vv --color=yes --strict-markers --instafail -nauto --no-cov --randomly-dont-reorganize --maxfail'
alias pytinf='pytest -ra -vv --color=yes --strict-markers --instafail -nauto -f'
alias pytinfc='pytest -ra -vv --color=yes --strict-markers --instafail -nauto -f --no-cov'
alias pytinfck='pytest -ra -vv --color=yes --strict-markers --instafail -nauto -f --no-cov --randomly-dont-reorganize -k'
alias pytinfcm='pytest -ra -vv --color=yes --strict-markers --instafail -nauto -f --no-cov --randomly-dont-reorganize --maxfail'
alias pytinfk='pytest -ra -vv --color=yes --strict-markers --instafail -nauto -f --randomly-dont-reorganize -k'
alias pytinfm='pytest -ra -vv --color=yes --strict-markers --instafail -nauto -f --randomly-dont-reorganize --maxfail'
alias pytink='pytest -ra -vv --color=yes --strict-markers --instafail -nauto --randomly-dont-reorganize -k'
alias pytinm='pytest -ra -vv --color=yes --strict-markers --instafail -nauto --randomly-dont-reorganize --maxfail'
alias pytk='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -k'
alias pytm='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize --maxfail'
alias pytn='pytest -ra -vv --color=yes --strict-markers -nauto'
alias pytnc='pytest -ra -vv --color=yes --strict-markers -nauto --no-cov'
alias pytncf='pytest -ra -vv --color=yes --strict-markers -nauto --no-cov -f'
alias pytncfi='pytest -ra -vv --color=yes --strict-markers -nauto --no-cov -f --instafail'
alias pytncfik='pytest -ra -vv --color=yes --strict-markers -nauto --no-cov -f --instafail --randomly-dont-reorganize -k'
alias pytncfim='pytest -ra -vv --color=yes --strict-markers -nauto --no-cov -f --instafail --randomly-dont-reorganize --maxfail'
alias pytncfk='pytest -ra -vv --color=yes --strict-markers -nauto --no-cov -f --randomly-dont-reorganize -k'
alias pytncfm='pytest -ra -vv --color=yes --strict-markers -nauto --no-cov -f --randomly-dont-reorganize --maxfail'
alias pytncfx='pytest -ra -vv --color=yes --strict-markers -nauto --no-cov -f --randomly-dont-reorganize -x'
alias pytncfxk='pytest -ra -vv --color=yes --strict-markers -nauto --no-cov -f --randomly-dont-reorganize -x --randomly-dont-reorganize -k'
alias pytnci='pytest -ra -vv --color=yes --strict-markers -nauto --no-cov --instafail'
alias pytncif='pytest -ra -vv --color=yes --strict-markers -nauto --no-cov --instafail -f'
alias pytncifk='pytest -ra -vv --color=yes --strict-markers -nauto --no-cov --instafail -f --randomly-dont-reorganize -k'
alias pytncifm='pytest -ra -vv --color=yes --strict-markers -nauto --no-cov --instafail -f --randomly-dont-reorganize --maxfail'
alias pytncik='pytest -ra -vv --color=yes --strict-markers -nauto --no-cov --instafail --randomly-dont-reorganize -k'
alias pytncim='pytest -ra -vv --color=yes --strict-markers -nauto --no-cov --instafail --randomly-dont-reorganize --maxfail'
alias pytnck='pytest -ra -vv --color=yes --strict-markers -nauto --no-cov --randomly-dont-reorganize -k'
alias pytncm='pytest -ra -vv --color=yes --strict-markers -nauto --no-cov --randomly-dont-reorganize --maxfail'
alias pytncx='pytest -ra -vv --color=yes --strict-markers -nauto --no-cov --randomly-dont-reorganize -x'
alias pytncxf='pytest -ra -vv --color=yes --strict-markers -nauto --no-cov --randomly-dont-reorganize -x -f'
alias pytncxfk='pytest -ra -vv --color=yes --strict-markers -nauto --no-cov --randomly-dont-reorganize -x -f --randomly-dont-reorganize -k'
alias pytncxk='pytest -ra -vv --color=yes --strict-markers -nauto --no-cov --randomly-dont-reorganize -x --randomly-dont-reorganize -k'
alias pytnf='pytest -ra -vv --color=yes --strict-markers -nauto -f'
alias pytnfc='pytest -ra -vv --color=yes --strict-markers -nauto -f --no-cov'
alias pytnfci='pytest -ra -vv --color=yes --strict-markers -nauto -f --no-cov --instafail'
alias pytnfcik='pytest -ra -vv --color=yes --strict-markers -nauto -f --no-cov --instafail --randomly-dont-reorganize -k'
alias pytnfcim='pytest -ra -vv --color=yes --strict-markers -nauto -f --no-cov --instafail --randomly-dont-reorganize --maxfail'
alias pytnfck='pytest -ra -vv --color=yes --strict-markers -nauto -f --no-cov --randomly-dont-reorganize -k'
alias pytnfcm='pytest -ra -vv --color=yes --strict-markers -nauto -f --no-cov --randomly-dont-reorganize --maxfail'
alias pytnfcx='pytest -ra -vv --color=yes --strict-markers -nauto -f --no-cov --randomly-dont-reorganize -x'
alias pytnfcxk='pytest -ra -vv --color=yes --strict-markers -nauto -f --no-cov --randomly-dont-reorganize -x --randomly-dont-reorganize -k'
alias pytnfi='pytest -ra -vv --color=yes --strict-markers -nauto -f --instafail'
alias pytnfic='pytest -ra -vv --color=yes --strict-markers -nauto -f --instafail --no-cov'
alias pytnfick='pytest -ra -vv --color=yes --strict-markers -nauto -f --instafail --no-cov --randomly-dont-reorganize -k'
alias pytnficm='pytest -ra -vv --color=yes --strict-markers -nauto -f --instafail --no-cov --randomly-dont-reorganize --maxfail'
alias pytnfik='pytest -ra -vv --color=yes --strict-markers -nauto -f --instafail --randomly-dont-reorganize -k'
alias pytnfim='pytest -ra -vv --color=yes --strict-markers -nauto -f --instafail --randomly-dont-reorganize --maxfail'
alias pytnfk='pytest -ra -vv --color=yes --strict-markers -nauto -f --randomly-dont-reorganize -k'
alias pytnfm='pytest -ra -vv --color=yes --strict-markers -nauto -f --randomly-dont-reorganize --maxfail'
alias pytnfx='pytest -ra -vv --color=yes --strict-markers -nauto -f --randomly-dont-reorganize -x'
alias pytnfxc='pytest -ra -vv --color=yes --strict-markers -nauto -f --randomly-dont-reorganize -x --no-cov'
alias pytnfxck='pytest -ra -vv --color=yes --strict-markers -nauto -f --randomly-dont-reorganize -x --no-cov --randomly-dont-reorganize -k'
alias pytnfxk='pytest -ra -vv --color=yes --strict-markers -nauto -f --randomly-dont-reorganize -x --randomly-dont-reorganize -k'
alias pytni='pytest -ra -vv --color=yes --strict-markers -nauto --instafail'
alias pytnic='pytest -ra -vv --color=yes --strict-markers -nauto --instafail --no-cov'
alias pytnicf='pytest -ra -vv --color=yes --strict-markers -nauto --instafail --no-cov -f'
alias pytnicfk='pytest -ra -vv --color=yes --strict-markers -nauto --instafail --no-cov -f --randomly-dont-reorganize -k'
alias pytnicfm='pytest -ra -vv --color=yes --strict-markers -nauto --instafail --no-cov -f --randomly-dont-reorganize --maxfail'
alias pytnick='pytest -ra -vv --color=yes --strict-markers -nauto --instafail --no-cov --randomly-dont-reorganize -k'
alias pytnicm='pytest -ra -vv --color=yes --strict-markers -nauto --instafail --no-cov --randomly-dont-reorganize --maxfail'
alias pytnif='pytest -ra -vv --color=yes --strict-markers -nauto --instafail -f'
alias pytnifc='pytest -ra -vv --color=yes --strict-markers -nauto --instafail -f --no-cov'
alias pytnifck='pytest -ra -vv --color=yes --strict-markers -nauto --instafail -f --no-cov --randomly-dont-reorganize -k'
alias pytnifcm='pytest -ra -vv --color=yes --strict-markers -nauto --instafail -f --no-cov --randomly-dont-reorganize --maxfail'
alias pytnifk='pytest -ra -vv --color=yes --strict-markers -nauto --instafail -f --randomly-dont-reorganize -k'
alias pytnifm='pytest -ra -vv --color=yes --strict-markers -nauto --instafail -f --randomly-dont-reorganize --maxfail'
alias pytnik='pytest -ra -vv --color=yes --strict-markers -nauto --instafail --randomly-dont-reorganize -k'
alias pytnim='pytest -ra -vv --color=yes --strict-markers -nauto --instafail --randomly-dont-reorganize --maxfail'
alias pytnk='pytest -ra -vv --color=yes --strict-markers -nauto --randomly-dont-reorganize -k'
alias pytnm='pytest -ra -vv --color=yes --strict-markers -nauto --randomly-dont-reorganize --maxfail'
alias pytnx='pytest -ra -vv --color=yes --strict-markers -nauto --randomly-dont-reorganize -x'
alias pytnxc='pytest -ra -vv --color=yes --strict-markers -nauto --randomly-dont-reorganize -x --no-cov'
alias pytnxcf='pytest -ra -vv --color=yes --strict-markers -nauto --randomly-dont-reorganize -x --no-cov -f'
alias pytnxcfk='pytest -ra -vv --color=yes --strict-markers -nauto --randomly-dont-reorganize -x --no-cov -f --randomly-dont-reorganize -k'
alias pytnxck='pytest -ra -vv --color=yes --strict-markers -nauto --randomly-dont-reorganize -x --no-cov --randomly-dont-reorganize -k'
alias pytnxf='pytest -ra -vv --color=yes --strict-markers -nauto --randomly-dont-reorganize -x -f'
alias pytnxfc='pytest -ra -vv --color=yes --strict-markers -nauto --randomly-dont-reorganize -x -f --no-cov'
alias pytnxfck='pytest -ra -vv --color=yes --strict-markers -nauto --randomly-dont-reorganize -x -f --no-cov --randomly-dont-reorganize -k'
alias pytnxfk='pytest -ra -vv --color=yes --strict-markers -nauto --randomly-dont-reorganize -x -f --randomly-dont-reorganize -k'
alias pytnxk='pytest -ra -vv --color=yes --strict-markers -nauto --randomly-dont-reorganize -x --randomly-dont-reorganize -k'
alias pytp='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize --pdb'
alias pytpc='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize --pdb --no-cov'
alias pytpck='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize --pdb --no-cov --randomly-dont-reorganize -k'
alias pytpcm='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize --pdb --no-cov --randomly-dont-reorganize --maxfail'
alias pytpcx='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize --pdb --no-cov --randomly-dont-reorganize -x'
alias pytpcxk='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize --pdb --no-cov --randomly-dont-reorganize -x --randomly-dont-reorganize -k'
alias pytpk='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize --pdb --randomly-dont-reorganize -k'
alias pytpm='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize --pdb --randomly-dont-reorganize --maxfail'
alias pytpx='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize --pdb --randomly-dont-reorganize -x'
alias pytpxc='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize --pdb --randomly-dont-reorganize -x --no-cov'
alias pytpxck='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize --pdb --randomly-dont-reorganize -x --no-cov --randomly-dont-reorganize -k'
alias pytpxk='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize --pdb --randomly-dont-reorganize -x --randomly-dont-reorganize -k'
alias pytx='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x'
alias pytxc='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x --no-cov'
alias pytxcf='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x --no-cov -f'
alias pytxcfk='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x --no-cov -f --randomly-dont-reorganize -k'
alias pytxcfn='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x --no-cov -f -nauto'
alias pytxcfnk='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x --no-cov -f -nauto --randomly-dont-reorganize -k'
alias pytxck='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x --no-cov --randomly-dont-reorganize -k'
alias pytxcn='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x --no-cov -nauto'
alias pytxcnf='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x --no-cov -nauto -f'
alias pytxcnfk='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x --no-cov -nauto -f --randomly-dont-reorganize -k'
alias pytxcnk='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x --no-cov -nauto --randomly-dont-reorganize -k'
alias pytxcp='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x --no-cov --randomly-dont-reorganize --pdb'
alias pytxcpk='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x --no-cov --randomly-dont-reorganize --pdb --randomly-dont-reorganize -k'
alias pytxf='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x -f'
alias pytxfc='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x -f --no-cov'
alias pytxfck='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x -f --no-cov --randomly-dont-reorganize -k'
alias pytxfcn='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x -f --no-cov -nauto'
alias pytxfcnk='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x -f --no-cov -nauto --randomly-dont-reorganize -k'
alias pytxfk='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x -f --randomly-dont-reorganize -k'
alias pytxfn='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x -f -nauto'
alias pytxfnc='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x -f -nauto --no-cov'
alias pytxfnck='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x -f -nauto --no-cov --randomly-dont-reorganize -k'
alias pytxfnk='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x -f -nauto --randomly-dont-reorganize -k'
alias pytxk='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x --randomly-dont-reorganize -k'
alias pytxn='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x -nauto'
alias pytxnc='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x -nauto --no-cov'
alias pytxncf='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x -nauto --no-cov -f'
alias pytxncfk='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x -nauto --no-cov -f --randomly-dont-reorganize -k'
alias pytxnck='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x -nauto --no-cov --randomly-dont-reorganize -k'
alias pytxnf='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x -nauto -f'
alias pytxnfc='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x -nauto -f --no-cov'
alias pytxnfck='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x -nauto -f --no-cov --randomly-dont-reorganize -k'
alias pytxnfk='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x -nauto -f --randomly-dont-reorganize -k'
alias pytxnk='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x -nauto --randomly-dont-reorganize -k'
alias pytxp='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x --randomly-dont-reorganize --pdb'
alias pytxpc='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x --randomly-dont-reorganize --pdb --no-cov'
alias pytxpck='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x --randomly-dont-reorganize --pdb --no-cov --randomly-dont-reorganize -k'
alias pytxpk='pytest -ra -vv --color=yes --strict-markers --randomly-dont-reorganize -x --randomly-dont-reorganize --pdb --randomly-dont-reorganize -k'
