# brew
eval "$(/opt/homebrew/bin/brew shellenv)"

# neovim
if command -v nvim &> /dev/null; then
	export EDITOR=nvim
else
	export EDITOR=vim
fi

# pipx
__dir="$HOME/.local/bin"
if [ -d "$__dir" ]; then
  export PATH="${PATH:+${PATH}:}__dir"
fi
