# brew
eval "$(/opt/homebrew/bin/brew shellenv)"

# neovim
if command -v nvim &> /dev/null; then
	export EDITOR=nvim
else
	export EDITOR=vim
fi

# zoxide
if command -v zoxide &> /dev/null; then
	eval "$(zoxide init zsh)"
fi
