#!/usr/bin/env sh

# brew
eval "$(/opt/homebrew/bin/brew shellenv)"

# neovim
if command -v lvim >/dev/null 2>&1; then
	export EDITOR=lvim
elif command -v nvim >/dev/null 2>&1; then
	export EDITOR=nvim
else
	export EDITOR=vim
fi
