#!/usr/bin/env zsh

# flutter
__dir="$HOME"/development/flutter/bin
case ":${PATH}:" in
*:"$__dir":*) ;;
*)
	export PATH="${__dir}:${PATH}"
	;;
esac

# node
if command -v brew >/dev/null 2>&1; then
	__dir="$(brew --prefix)"/opt/node@20/bin
	case ":${PATH}:" in
	*:"$__dir":*) ;;
	*)
		export PATH="${__dir}:${PATH}"
		;;
	esac
fi

# pipx
__dir="${HOME}"/.local/bin
case ":${PATH}:" in
*:"${__dir}":*) ;;
*)
	export PATH="${__dir}:${PATH}"
	;;
esac

# rust
__dir="${HOME}"/.cargo/bin
case ":${PATH}:" in
*:"${__dir}":*) ;;
*)
	export PATH="${__dir}:${PATH}"
	;;
esac
