#!/usr/bin/env zsh

export EDITOR=vim
export MKL_NUM_THREADS=1
export PATH="$HOME/.dotfiles/bin${PATH:+:${PATH}}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$USER}"

# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(~/miniconda3/bin/conda shell.zsh hook 2>/dev/null)"
if [ $? -eq 0 ]; then
  eval "$__conda_setup"
else
  if [ -f ~/miniconda3/etc/profile.d/conda.sh ]; then
    # shellcheck source=/dev/null
    . ~/miniconda3/etc/profile.d/conda.sh
  else
    export PATH="$HOME/miniconda3/bin${PATH:+:${PATH}}"
  fi
fi
unset __conda_setup
# <<< conda init <<<
