#!/usr/bin/env sh

# bump2version
alias bp='bump2version patch --allow-dirty'
alias bp-major='bump2version major --allow-dirty'
alias bp-minor='bump2version minor --allow-dirty'

# bat
alias cat=batcat

# cd
alias ~='cd ~'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias cddb='cd $PATH_DROPBOX'
alias cddf='cd $PATH_DOTFILES'
alias cddt='cd ~/Desktop'
alias cdw='cd ~/work'

# conda
alias ceu='conda env update --prune'

# dotfiles
alias gitconfig='$EDITOR ~/.config/git/config'
alias gitignore='$EDITOR ~/.config/git/ignore'
alias i3config='$EDITOR ~/.config/i3/config'
alias tmuxconf='$EDITOR ~/.tmux.conf'
alias vimrc='$EDITOR ~/.vimrc'
alias zshenv='$EDITOR ~/.zshenv'
alias bashrc='$EDITOR ~/.bashrc'
alias rebashrc='. ~/.zshrc'
alias set-dotfiles-to-ssh="cddf && gremset origin git@github.com:dycw/dotfiles.git"

# evince
alias ev='evince'

# find
alias fd=fdfind
alias fdd='fd --type=directory'
alias fde='fd --type=executable'
alias fdf='fd --type=file'
alias fds='fd --type=symlink'



# grep
alias grep='grep --color'

# hypothesis
alias hypothesis-ci='export HYPOTHESIS_PROFILE=ci'
alias hypothesis-debug='export HYPOTHESIS_PROFILE=debug'
alias hypothesis-default='export HYPOTHESIS_PROFILE=default'
alias hypothesis-dev='export HYPOTHESIS_PROFILE=dev'

# ib gateway
alias ib-gateway=~/Jts/ibgateway/978/ibgateway

# jupyter
alias juplab='jupyter lab'
alias jupnb='jupyter notebook'

# ls
alias l='ls -l --classify --color --human-readable --time-style=long-iso'
alias la='ls -hl --almost-all --classify --color --time-style=long-iso'
alias ld='ls -lt --classify --color --human-readable --reverse --time-style=long-iso'
alias lda='ls -lt --almost-all --classify --color --human-readable --reverse --time-style=long-iso'
alias lh='ls -l --classify --color --directory --human-readable .*'
alias lr='ls --classify --color --human-readable --recursive'
alias lra='ls --almost-all --classify --color --recursive'

# pre-commit
alias pc='$(git rev-parse --show-toplevel)/.git/hooks/pre-commit'

# python
alias p='python'

# python install
alias pyinstall='pip install hvplot jupyterlab pyinstrument-decorator seaborn'

# python-path
alias pypath='export PYTHONPATH=.'

# tensorboard
alias tb='tensorboard --logdir .'

# vim
alias v=vim
