#!/usr/bin/env bash
# shellcheck source=/dev/null

# env
__file="${HOME}/dotfiles/shell/env.sh"
if [ -f "${__file}" ]; then
	. "${__file}"
fi

# bashrc
__file="${HOME}/.bashrc"
if [ -f "${__file}" ]; then
	. "${__file}"
fi

. "$HOME/.local/bin/env"
