#!/usr/bin/env bash
# shellcheck disable=SC1090

# Set $PATH_DOTFILES
PATH_DOTFILES="$(dirname "$(dirname "$(readlink --canonicalize-existing "${BASH_SOURCE[0]}")")")"
export PATH_DOTFILES
PATH="$PATH_DOTFILES/bin${PATH:+:${PATH}}"

# If not running interactively, don't do anything
case $- in
*i*) ;;
*) return ;;
esac

# some settings
shopt -s histappend
shopt -s checkwinsize
#shopt -s globstar

declare -a scripts=()
scripts+=("bash/aliases")
scripts+=("bash/configure_bash")
scripts+=("bash/start_dropbox")
scripts+=("bash/start_bash_it")
scripts+=("bash/ultimate_git_aliases")
scripts+=("conda/init")
for script in "${scripts[@]}"; do
	path_script="$PATH_DOTFILES/$script"
	if [ -f "$path_script" ]; then
		source "$path_script"
	else
		printf "%(%Y-%m-%d %H:%M:%S)T: Unable to find %s\n" -1 "$path_script"
	fi
done
