#!/usr/bin/env bash
# shellcheck disable=SC1090

# set PATH_DOTFILES
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
	PATH_DOTFILES="$(cd -P "$(dirname "$SOURCE")" && pwd)"
	SOURCE="$(readlink "$SOURCE")"
	[[ $SOURCE != /* ]] && SOURCE="$PATH_DOTFILES/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
PATH_DOTFILES="$(dirname "$(dirname "$SOURCE")")"
export PATH_DOTFILES
PATH="$PATH_DOTFILES/bin${PATH:+:${PATH}}"

# More env vars
export EDITOR=vim
export FLASK_DEBUG=1
export MKL_NUM_THREADS=1
export PATH_DROPBOX="/data/derek/Dropbox"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$USER}"

# https://unix.stackexchange.com/a/541352
if [ -n "$BASH_VERSION" ]; then
	# include .bashrc if it exists
	if [ -f "$HOME/.bashrc" ]; then
		. "$HOME/.bashrc"
	fi
fi
