name: pull-request

on:
  pull_request:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run bump-version
        run: CI=1 ./.repo/actions/bump-version.sh

  markdownlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Run markdownlint
        run: CI=1 ./.repo/actions/markdownlint.sh

  prettier:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Run prettier
        run: CI=1 ./.repo/actions/prettier.sh

  shellcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Run shellcheck
        run: CI=1 ./.repo/actions/shellcheck.sh

  shfmt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Run shfmt
        run: CI=1 ./.repo/actions/shfmt.sh

  taplo:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Run taplo
        run: CI=1 ./.repo/actions/taplo.sh

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: CI=1 ./.repo/actions/test.sh
