name: push

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Tag the latest commit
        run: CI=1 ./.repo/actions/git-tag.sh
